# Generated by Django 5.1.2 on 2024-10-18 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="alert",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="alert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="city",
            name="country_code",
            field=models.CharField(default="IN", max_length=2),
        ),
        migrations.AlterField(
            model_name="alert",
            name="message",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="threshold",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thresholds",
                to="weather.city",
            ),
        ),
        migrations.AlterField(
            model_name="threshold",
            name="consecutive_updates",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="threshold",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thresholds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailysummary",
            unique_together={("city", "date")},
        ),
    ]
