# Generated by Django 5.1.2 on 2024-10-18 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_rename_timestamp_alert_created_at_alert_is_active_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherdata",
            unique_together={("city", "timestamp")},
        ),
    ]
