# Generated by Django 5.1.2 on 2024-10-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_alter_weatherdata_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailysummary",
            name="dominant_reasoning",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temp", models.FloatField()),
                ("feels_like", models.FloatField()),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("main", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
            options={
                "unique_together": {("city", "timestamp")},
            },
        ),
    ]
