# Generated by Django 5.1.2 on 2024-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_city_latitude_city_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
