# Generated by Django 5.1.2 on 2024-10-18 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0005_city_altitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="is_active",
        ),
    ]
