# Generated by Django 5.1.2 on 2024-10-18 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0006_remove_alert_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailysummary",
            old_name="average_temp",
            new_name="avg_humidity",
        ),
        migrations.RemoveField(
            model_name="dailysummary",
            name="dominant_condition",
        ),
        migrations.RemoveField(
            model_name="dailysummary",
            name="dominant_reasoning",
        ),
        migrations.AddField(
            model_name="dailysummary",
            name="avg_temp",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailysummary",
            name="avg_wind_speed",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
