# Generated by Django 5.1.2 on 2024-10-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0008_dailysummary_dominant_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country_code",
            field=models.CharField(default="IN", max_length=4),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_data",
                to="weather.city",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
