# Generated by Django 5.1.2 on 2024-10-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0009_alter_city_country_code_alter_weatherdata_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
